#ifndef __ControllerFrame__
#define __ControllerFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

//// end generated include

/** Implementing Frame */
class ControllerFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void OnButtonClick_ConvertToGrayscale( wxCommandEvent& event );
		void OnButtonClick_Duotone( wxCommandEvent& event );
		void OnButtonClick_PickColour( wxCommandEvent& event );
		void OnCheckBox_KeepOneHue( wxCommandEvent& event );
		//void OnScrollChanged_HueIntesivity( wxScrollEvent& event );
		void OnScrollThumbTrack_HueIntesivity(wxScrollEvent& event);
		void OnText_ChangeHueIntensivity( wxCommandEvent& event );
		void OnButtonClick_RaspberriesButton( wxCommandEvent& event );
		//void OnScrollChanged_ChangeRedChannel( wxScrollEvent& event );
		void OnScrollThumbTrack_ChangeRedChannel(wxScrollEvent& event);
		void OnText_ChangeRedChannel( wxCommandEvent& event );
		//void OnScrollChanged_ChangeGreenChannel( wxScrollEvent& event );
		void OnScrollThumbTrack_ChangeGreenChannel(wxScrollEvent& event);
		void OnText_ChangeGreenChannel( wxCommandEvent& event );
		//void OnScrollChanged_ChangeBlueChannel( wxScrollEvent& event );
		void OnScrollThumbTrack_ChangeBlueChannel(wxScrollEvent& event);
		void OnText_ChangeBlueChannel( wxCommandEvent& event );
		void OnMenuSelection_LoadImage( wxCommandEvent& event );
		void OnMenuSelection_LoadConfig( wxCommandEvent& event );
		void OnMenuSelection_SaveImage( wxCommandEvent& event );
		void OnMenuSelection_SaveConfig( wxCommandEvent& event );
		void OnMenuSelection_Exit( wxCommandEvent& event );
		void OnMenuSelection_GoFullscreen( wxCommandEvent& event );
	public:
		/** Constructor */
		ControllerFrame( wxWindow* parent, Model& newModel );
	//// end generated class members
	
};

#endif // __ControllerFrame__
